version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
      build:
        patterns:
          - "esbuild"
          - "typescript"
          - "mocha"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
